### ISSUE TITLE
Rambox preventing computer from sleep

### ISSUE THREAD

**Issue by guedressel** [saenzramiro/rambox#511]
### Steps to reproduce

Run Rambox

### Expected behavior

After leaving the computer alone for a couple of minutes it may first switch the display to standby and later bring the computer to sleep.

### Actual behavior

Computer doesn't switch off display and does not enter sleep mode as long as Rambox is running.

### ENVIRONMENT

> Rambox: v0.4.5

> OS: Linux - Kubuntu 16.04

> Arch: x64

**Comment by weeman1337** [comment]
Working for me on Ubuntu 16.10 :/

Do you use the Rambox account? Which services do you use?

**Comment by guedressel** [comment]
Yes - I'm using a rambox account.
Services running:
  - Hangouts (2x)
  - Wire
  - TweetDeck
  - HipChat

Services disabled:
  - Zimbra

**Comment by MakisH** [comment]
Try disabling some services to see if it is caused by one of them. I say that because Wire for example has a [relevant bug](https://github.com/wireapp/wire-webapp/issues/687) in Firefox, which doesn't correctly end a (received) call. I guess this could also prevent the computer from going to sleep.

**Comment by guedressel** [comment]
I haven't experienced this issue in a while.
Might be that recent Rambox updates fixed it or that it really was an issue of a service (and it was fixed there)
@MakisH I stopped using Wire, but yesterday I enabled it for testing: My Computer went to sleep. Hence no issue there.

Conclusion: This doesn't affect me anymore.

**Comment by spielkind** [comment]
I still have this issue, with HipChat enabled, when I disable HipChat everything works, as expected.
(I use: Skype, Slack, WhatsApp (2x), Hangouts, Facebook, Steam, HipChat)
